### ISSUE TITLE
Installation Guide?

### ISSUE THREAD

**Issue by ymilord** [luwes/LIFX-Menu#2]
I ran 'sudo python setup.py install' it ran that with no errors, But when I launch the app it then it throws an error. In the console is shows 'Menu[60548]: ImportError: No module named lifx' & 'LIFX Menu[60548]: LIFX Menu Error'

Any suggestions?

Thanks!

**Comment by luwes** [comment]
Can you try running `python setup.py py2app` with sudo prepended or not and let me know. Cheers

**Comment by ymilord** [comment]
Awesome that seemed to work. Thanks!

After I launched the app, It was in a hung state until I fired up the LiFX app on iOS. In the pull down it only shows about half of the bulbs and its listing them by MAC address. I assume is going to take a bit before I finds them all. Is there a way to rename the bulbs? Or pull the name/tags of the existing ones?

**Comment by luwes** [comment]
Cool! I've noticed the hanging too. We probably need to start using the official LIFX API (https://github.com/lifx) instead of the reverse engineered one which is currently in place. No way to rename the bulbs for now. I understand that this would be not so user friendly if you have a lot of bulbs :smile:

**Comment by ymilord** [comment]
Ah Okay. 

Thanks again for all the help!

**Comment by luwes** [comment]
Just pushed an update that tries to use the bulb labels (they have to be set beforehand on mobile)

![screen shot 2014-05-19 at 15 48 56](https://cloud.githubusercontent.com/assets/360826/3014845/90f87684-df5c-11e3-8317-fe10b8dc9279.png)

**Comment by kapps7** [comment]
Hi, I am getting an indent error when trying to install:

 File "setup.py", line 1
    """
    ^
IndentationError: unexpected indent
Ok quick 'crash course' juste deleted those comment lines :) Working Cool! A big thank you and a big request to add keyboard controls whenever you can. Thanks.
