### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by davidhq** [luwes/LIFX-Menu#8]
I only see this:
![screen shot 2014-12-10 at 15 38 43](https://cloud.githubusercontent.com/assets/3899/5377467/abbeab60-8082-11e4-8cf2-25f9f3961ed8.png)

And even that option does nothing... What could be wrong?

**Comment by luwes** [comment]
@davidhq I'm not sure, could be something with OSX Yosemite. I'm not maintaining this anymore since LIFX support said it was developing its own OSX app. That was a few months ago.

**Comment by davidhq** [comment]
I'm on 10.9.5 actually... ok, no problem, thank you for the information!
